
# the category
country = 'Austria'

city = 'Vienna'

itinerary_name = 'Day in Vienna'

abstract = '''
A quick daytrip to Vienna, Austria. Fly out via Stansted after work, hack it in a hostel for the night, or in the airport, then explore for the day, and flyback the 2 days later. 
'''

trip_length = "1 day"

[[travel]]
type = "Plane"
departure = "London (any)"
arrival = "Vienna"
time_type = "Depart by"
time_time = "17:00, Friday"

[[travel]]
type = "Plane"
departure = "Vienna"
arrival = "London (any)"
time_type = "Arrive by"
time_time = "10:00, Sunday"

[[accom]]
type = "Sleep"
name = "Vienna Airport"
location = "Airport"
duration = "8 hours"
check_in = "23:00 Friday"
check_out = "6:00 Sunday"

[[visits]]
title = "Historic Center of Vienna"
notes = "Visit whenever"

[[visits]]
title = "Historic Center of Vienna"
notes = "Visit dsa"

[[visits]]
title = "Historic Center of Vienna"
notes = "Visit das"

